version: "3.9"
services:
  vue-app:
    build: 
      context: ./pathfinding-vue
    ports: 
      - target: 80
        published: 8000

  backend-app:
    build:
      context: ./pathfinding
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - target: 80
        published: 8001